name: Ch2 CI Checks

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Ch2 App
    runs-on: ubuntu-latest
    steps:
    
    # Caches and restores the bazelisk download directory, the bazel build directory.
    - name: Cache bazel
      uses: actions/cache@v2.1.4
      env:
        cache-name: bazel-cache
      with:
        path: |
          ~/.cache/bazelisk
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: bazel build //ch2
    
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
          name: api
          path: ../bazel-out/k8-fastbuild-ST-*/bin/ch2/ch2_/ch2
