name: Chapter 3 Checks

on:
  push:
    branches: # <1>
      - main
defaults:
  run:
    working-directory: ./ch3
jobs:
 test:
    name: Test Application
    runs-on: ubuntu-latest # <2>
    steps:
    - name: Set up Go 1.x # <3>
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out code into the Go module directory # <4>
      uses: actions/checkout@v2
    - name: Run Test
      run: go test ./...  # <5>
  build:
    name: Build App
    runs-on: ubuntu-latest #
    steps:

    - name: Set up Go 1.x #
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory #
      uses: actions/checkout@v2

    - name: Build
      run: make build #

    - name: Copy Files #
      run: |
           mkdir  artifacts
           cp api artifacts/.

    - name: Archive #
      uses: actions/upload-artifact@v2
      with:
          name: api #
          path: artifacts