name: CI Checks

on:
  push:
    branches: # <1>
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest # <2>
    steps:
    
    - name: Set up Go 1.x # <3>
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    
    - name: Check out code into the Go module directory # <4>
      uses: actions/checkout@v2
      
    - name: Build
      run: make build # <5>
    
    - name: Copy Files # <6>
      run: |
           mkdir  artifacts
           cp api artifacts/.

    - name: Archive # <7>
      uses: actions/upload-artifact@v2
      with:
          name: api # <8>
          path: artifacts